FROM python:3.12-slim

WORKDIR /app

# Устанавливаем системные зависимости для сборки psycopg2 и других пакетов
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "telegram_bot/bot.py"]
