# Generated by Django 5.1.7 on 2025-08-21 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('booking', '0001_initial'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationassignment',
            name='moderator',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_moderator': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationassignment',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_assignment', to='booking.property'),
        ),
        migrations.AddField(
            model_name='supportassignment',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_assignment', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='supportassignment',
            name='support',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_support': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminpanel_support_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
