# Generated by Django 5.1.7 on 2025-05-25 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportassignment',
            name='support',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_support': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adminpanel_support_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
