# Generated by Django 5.1.7 on 2025-05-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='support_operator',
        ),
    ]
