# Generated by Django 5.1.7 on 2025-07-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("host", "Host"),
                    ("admin", "Admin"),
                    ("blog_editor", "Blog Editor"),
                ],
                default="user",
                max_length=50,
            ),
        ),
    ]
