# Generated by Django 5.1.7 on 2025-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_review_review_type_review_to_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
