# Generated by Django 5.1.7 on 2025-05-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
