# Generated by Django 5.1.7 on 2025-04-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20250401_1927'),
    ]

    operations = [
    ]
