# Generated by Django 5.1.7 on 2025-05-22 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_delete_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilitycalendar',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='availabilitycalendar',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='availabilitycalendar',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='availabilitycalendar',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.property'),
        ),
    ]
