# Generated by Django 5.1.7 on 2025-05-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_availabilitycalendar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='availabilitycalendar',
            options={'verbose_name_plural': 'Availability Calendar'},
        ),
        migrations.AlterField(
            model_name='availabilitycalendar',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='availabilitycalendar',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='booking.property'),
        ),
        migrations.AlterUniqueTogether(
            name='availabilitycalendar',
            unique_together={('property', 'date')},
        ),
    ]
