# Generated by Django 5.1.7 on 2025-04-10 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availabilitycalendar",
            options={"verbose_name_plural": "Availability Calendar"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="propertyamenity",
            options={"verbose_name_plural": "Property Amenities"},
        ),
        migrations.AlterModelOptions(
            name="propertyphoto",
            options={"ordering": ["order_index"]},
        ),
        migrations.RemoveField(
            model_name="propertyphoto",
            name="url",
        ),
        migrations.AddField(
            model_name="amenity",
            name="icon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="propertyphoto",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_photos/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="socialauth",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="amenity",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="availabilitycalendar",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="availabilitycalendar",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="availabilitycalendar",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability",
                to="booking.property",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.property",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="booking.booking",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("booking_request", "Booking Request"),
                    ("booking_confirmed", "Booking Confirmed"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("payment_received", "Payment Received"),
                    ("review_received", "Review Received"),
                    ("message_received", "Message Received"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="booking.booking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Credit Card"),
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="guest_capacity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("villa", "Villa"),
                    ("cabin", "Cabin"),
                    ("cottage", "Cottage"),
                    ("loft", "Loft"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="room_count",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="propertyamenity",
            name="amenity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_amenities",
                to="booking.amenity",
            ),
        ),
        migrations.AlterField(
            model_name="propertyamenity",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_amenities",
                to="booking.property",
            ),
        ),
        migrations.AlterField(
            model_name="propertyphoto",
            name="order_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="propertyphoto",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="booking.property",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="booking.booking",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="booking.property",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="socialauth",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("apple", "Apple"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="socialauth",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_auth",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("host", "Host"), ("admin", "Admin")],
                default="user",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userrating",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userrating",
            name="rating",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="availabilitycalendar",
            unique_together={("property", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="propertyamenity",
            unique_together={("property", "amenity")},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("booking", "author")},
        ),
        migrations.AlterUniqueTogether(
            name="socialauth",
            unique_together={("provider", "provider_id")},
        ),
        migrations.AlterUniqueTogether(
            name="userrating",
            unique_together={("from_user", "to_user")},
        ),
    ]
