# Generated by Django 5.1.7 on 2025-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_availability_alter_availabilitycalendar_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
