# Generated by Django 5.1.7 on 2025-06-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_alter_review_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_url",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
