# Generated by Django 5.1.7 on 2025-08-21 12:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('seo_title', models.CharField(blank=True, help_text=' SEO заголовок (title) — показывается в поисковике. До 60 символов.', max_length=255)),
                ('seo_description', models.TextField(blank=True, help_text=' SEO описание (description) — краткое описание статьи. До 160 символов.', max_length=300)),
            ],
        ),
    ]
