# Generated by Django 5.1.7 on 2025-07-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="seo_description",
            field=models.TextField(
                blank=True,
                help_text=" SEO описание (description) — краткое описание статьи. До 160 символов.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="seo_title",
            field=models.CharField(
                blank=True,
                help_text=" SEO заголовок (title) — показывается в поисковике. До 60 символов.",
                max_length=255,
            ),
        ),
    ]
